version: 2.11.25
description: HTTP reverse proxy and load balancer
homepage: https://traefik.io
license:
  identifier: MIT
  url: https://github.com/traefik/traefik/blob/master/LICENSE.md
changelog: https://github.com/traefik/traefik/releases/tag/v2.11.25
notes: Run with a configuration file 'traefik -c <yourconfig.toml>' or 'traefik --help' for all options.
architecture:
  64bit:
    url: https://github.com/traefik/traefik/releases/download/v2.11.25/traefik_v2.11.25_windows_amd64.zip
    hash: 4e329bb8c5818a07aa3457a974ddc4a0b23a9e5796eb6c1119bbc01e3d58b220
  32bit:
    url: https://github.com/traefik/traefik/releases/download/v2.11.25/traefik_v2.11.25_windows_386.zip
    hash: 7e01ca8c5227c6ba2498291386d865cd7d23ccf46dc7ff7912f0d4ee9f9ffd7a
  arm64:
    url: https://github.com/traefik/traefik/releases/download/v2.11.25/traefik_v2.11.25_windows_arm64.zip
    hash: 8b49b08ff0e0e21bf9006380713b165faf055b998d816efa2c76f6a9e3cdd6a1
bin: traefik.exe
checkver:
  url: https://api.github.com/repos/traefik/traefik/releases
  regex: '"v?(2\.[\d.]+)"'
autoupdate:
  changelog: https://github.com/traefik/traefik/releases/tag/v$version
  architecture:
    64bit:
      url: https://github.com/traefik/traefik/releases/download/v$version/traefik_v$version_windows_amd64.zip
    32bit:
      url: https://github.com/traefik/traefik/releases/download/v$version/traefik_v$version_windows_386.zip
    arm64:
      url: https://github.com/traefik/traefik/releases/download/v$version/traefik_v$version_windows_arm64.zip
  hash:
    url: $baseurl/traefik_v$version_checksums.txt
